spring:
  profiles:
    active: mssql
  quartz:
    auto-startup: false
    job-store-type: jdbc
    timezone: Asia/Seoul
  rest-template:
    connect-timeout-sec: 5
    read-timeout-sec: 1800
  datasource:
    name: T3SERIES
    hikari:
      minimum-idle: 30
      maximum-pool-size: 150
      pool-name: SpringBootJPAHikariCP
      idle-timeout: 60000
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        proc:
          param_null_passing: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB

server:
  port: 8080
  compression:
    enabled: true
  tomcat:
    max-http-form-post-size: 1024MB
  error:
    whitelabel:
      enabled: false
  servlet:
    context-real-path:
    context-path: /
    session:
      cookie:
        name: T3SESSIONID

app:
  corporation:
  languages:
    - en
    - ja
    - ko
    - zh
  authentication:
    login-url: login
    default-url: home
    cors-allow-url:
      - http://localhost:3000
    cors-allow-path:
      - /sso/**
    password-policy:
      usable-username: false
      min-length: 8
      max-repeat: 3
      lcredit: 1
      ucredit: 1
      dcredit: 1
      ocredit: 1
      max-reuse-prevention: 0
    login-policy:
      max-failure-count: 5
      long-term-unvisited-days: 0
      max-password-days: 0
    account:
      system-admins:
        - admin
    initial-password: T3SmartSCM!
  service:
    file:
      external-path: C:/Wingui/
      name: file
      category:
        system: system
        noticeboard: noticeboard
        temporary: temporary
        excel: upload-excel
        issue: issue
        calendar: calendar
        meeting: meeting
      temporary-clean-fixed-rate: 86400000
    mailing:
      polling-rate: 50000
      smtp:
        host: 59.19.252.148
        port: 25
        username: dev01@zionex.com
        password: vivazio0527#
        encoding: UTF-8
        mailagentip: nomail
        protocols: TLSv1.2
        trust: 59.19.252.148
  server:
    bf:
      id: T3SeriesBF
      host: localhost
    dp:
      id: T3SeriesDP
      host: localhost
    mp:
      id: T3SeriesMP
      host: localhost
    fp:
      id: T3SeriesFP
      host: localhost
  cache:
    enable: true
  session:
    token-valid-timeout: 43200
    timeout: 3600

--- # MSSQL
spring:
  config:
    activate:
      on-profile: mssql
  datasource:
    url: jdbc:sqlserver://192.168.3.28:1433;database=T3SMARTSCM
    username: sa
    password: Vivazio2025!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect

--- # ORACLE
spring:
  config:
    activate:
      on-profile: oracle
  sql:
    init:
      platform: oracle
  datasource:
    url: jdbc:oracle:thin:@192.168.3.28:1521:zionex
    username: T3SMARTSCM
    password: T3SMARTSCM
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
